### ISSUE TITLE
Releasing to Bintray

### ISSUE THREAD

**Issue by sdelamo** [robertoschwald/schwartz-monitor#2]
Hello @robertoschwald 

Any plans of releasing this plugin to Bintray ?

**Comment by robertoschwald** [comment]
I've now merged the rewrite branch into master. The plugin works here since some months with the Schwartz plugin pretty well and should also work with the Quartz plugin now, but I need some feedback if it runs with Quartz as well as I don't have time currently to test with Quartz. If it does, I might send a PR to the Quartz-Monitor repo.

**Comment by robertoschwald** [comment]
PR sent to quartz-monitor, as this plugin should support both Quartz plugins.

Quick-Test with a sample Grails 3 application, the Quartz plugin and the Quartz Monitor plugin branch containing my backported features showed that it indeed works with Quartz Monitor  as well.

https://github.com/jamescookie/quartz-monitor/pull/42

**Comment by sdelamo** [comment]
Thanks @robertoschwald

**Comment by robertoschwald** [comment]
schwartz-monitor is released as an own plugin to bintray.
